apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-loginapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
 
  source:
    repoURL: https://github.com/ilyasjaelani/simple-loginapp-gitops
    targetRevision: main
    path: apps/simple-loginapp
 
  destination:
    server: https://kubernetes.default.svc
    namespace: pro
 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas